# netlify.toml

[build]
  # Build command: first build React, then Eleventy, then copy React output into Eleventy output
  command = "npm run build"
  
  # Publish directory: where Eleventy outputs the static site
  publish = "_site"

# Redirect rule: allows React client-side routing to work (e.g., /quizzes, /about)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
